[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["export NODE_OPTIONS='--max-old-space-size=2048'", "npx rimraf .cache build dist .strapi", "npm run build"]

[start]
cmd = "npm start"
