services:
  - type: web
    name: revolverrift-backend
    runtime: node
    rootDir: backend
    buildCommand: rm -rf .cache dist build .strapi node_modules/.cache && npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
